name: 'home-ims'

volumes:
  eventstore-data:
    name: hims-eventstore-data
    driver: local
  eventstore-logs:
    name: hims-eventstore-logs
    driver: local
  read-model-data:
    name: hims-read-model-data
    driver: local

secrets:
  hims-mariadb-rootpw:
    file: ./.secrets/hims-mariadb-rootpw
  hims-mariadb-pw:
    file: ./.secrets/hims-mariadb-pw

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: hims-server
    container_name: hims-server
    depends_on:
      - eventstore
    ports:
    # TODO Find a way to differentiate between dev and prod port mapping
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=thisisatest
    volumes:
      - ~/.aspnet/https:/https:ro
    #secrets:
      #- hims-mariadb-pw

  eventstore:
    image: eventstore/eventstore:24.2.0-jammy
    container_name: hims-eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_ALLOW_ANONYMOUS_STREAM_ACCESS=true
    ports:
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-logs
        target: /var/log/eventstore

  readmodeldb:
    image: mariadb:11.5.2
    container_name: hims-db
    restart: unless-stopped
    #networks:
    #  - dbaccess
    secrets:
      - hims-mariadb-rootpw
      - hims-mariadb-pw
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/hims-mariadb-rootpw
      - MARIADB_DATABASE=hims-db
      - MARIADB_USER=hims
      - MARIADB_PASSWORD_FILE=/run/secrets/hims-mariadb-pw
    volumes:
      - read-model-data:/var/lib/mysql
