services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: hims-server
    container_name: hims-server
    depends_on:
      - eventstore
      - db
    ports:
      - 80:80
      - 443:443
    secrets:
      - hims-rootpw
      - hims-db-rootpw
      - hims-db-userpw
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=thisisatest # TODO this would no longer be a test...
    volumes:
      - ~/.aspnet/https:/https:ro
    #secrets:
      #- hims-mariadb-pw
