name: 'home-ims'

volumes:
  eventstore-data:
    name: hims-eventstore-data
    driver: local
  eventstore-logs:
    name: hims-eventstore-logs
    driver: local
  db-data:
    name: hims-db-data
    driver: local

secrets:
  hims-rootpw:
    file: ./.secrets/hims-rootpw
  hims-db-rootpw:
    file: ./.secrets/hims-db-rootpw
  hims-db-userpw:
    file: ./.secrets/hims-db-userpw

services:
  eventstore:
    image: eventstore/eventstore:24.2.0-jammy
    container_name: hims-eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_ALLOW_ANONYMOUS_STREAM_ACCESS=true
    ports:
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-logs
        target: /var/log/eventstore

  db:
    image: mariadb:11.7.2
    container_name: hims-db
    restart: unless-stopped
    #networks:
    #  - dbaccess
    secrets:
      - hims-db-rootpw
      - hims-db-userpw
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/hims-db-rootpw
      - MARIADB_DATABASE=IdentityStore
      - MARIADB_USER=hims-identity
      - MARIADB_PASSWORD_FILE=/run/secrets/hims-db-userpw
    volumes:
      - db-data:/var/lib/mysql
