name: 'home-ims'

volumes:
  eventstore-data:
    name: hims-eventstore-data
    driver: local
  db-data:
    name: hims-db-data
    driver: local

secrets:
  hims-rootpw:
    file: ./.secrets/hims-rootpw
  hims-eventstore-rootpw:
    file: ./.secrets/hims-eventstore-rootpw
  hims-db-rootpw:
    file: ./.secrets/hims-db-rootpw
  hims-db-userpw:
    file: ./.secrets/hims-db-userpw

services:
  eventstore:
    image: postgres:17.4
    container_name: hims-eventstore
    secrets:
      - hims-eventstore-rootpw
    environment:
      - POSTGRES_USER=hims-eventstore
      - POSTGRES_PASSWORD_FILE=/run/secrets/hims-eventstore-rootpw
    volumes:
      - type: volume
        source: eventstore-data
        target: /var/lib/postgresql/data

  db:
    image: mariadb:11.7.2
    container_name: hims-db
    restart: unless-stopped
    #networks:
    #  - dbaccess
    secrets:
      - hims-db-rootpw
      - hims-db-userpw
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/hims-db-rootpw
      - MARIADB_DATABASE=IdentityStore
      - MARIADB_USER=hims-identity
      - MARIADB_PASSWORD_FILE=/run/secrets/hims-db-userpw
    volumes:
      - db-data:/var/lib/mysql
