version: '3.4'

networks:
  dbaccess:
    name: hims-dbaccess
    driver: bridge

volumes:
  dbdata:
    name: hims-dbdata
    driver: local

secrets:
  hims-mariadb-rootpw:
    file: ./.secrets/hims-mariadb-rootpw
  hims-mariadb-pw:
    file: ./.secrets/hims-mariadb-pw

services:
  app:
    profiles:
      - all
      - app
    build:
      context: .
      dockerfile: HomeIMS.dockerfile
    image: hims-app
    container_name: hims-app
    depends_on:
      - db
    networks:
      - dbaccess
    ports:
    # TODO Find a way to differentiate between dev and prod port mapping
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=thisisatest
    volumes:
      - ~/.aspnet/https:/https:ro
    secrets:
      - hims-mariadb-pw

  db:
    profiles:
      - all
      - backend
    image: mariadb
    container_name: hims-db
    restart: unless-stopped
    networks:
      - dbaccess
    secrets:
      - hims-mariadb-rootpw
      - hims-mariadb-pw
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/hims-mariadb-rootpw
      - MARIADB_DATABASE=hims-db
      - MARIADB_USER=hims
      - MARIADB_PASSWORD_FILE=/run/secrets/hims-mariadb-pw
    volumes:
      - dbdata:/var/lib/mysql
